### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ply00** [ai-winter/python_motion_planning#19]
While I am running the setup.py, the error comes out like:
D:\ProgramFiles\anaconda\envs\winter\python.exe D:\py\pythonProject\python_motion_planning-master\setup.py 
Traceback (most recent call last):
  File "D:\py\pythonProject\python_motion_planning-master\setup.py", line 3, in <module>
    setup(
  File "D:\ProgramFiles\anaconda\envs\winter\lib\site-packages\setuptools\__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "D:\ProgramFiles\anaconda\envs\winter\lib\site-packages\setuptools\_distutils\core.py", line 157, in setup
    dist.parse_config_files()
  File "D:\ProgramFiles\anaconda\envs\winter\lib\site-packages\setuptools\dist.py", line 648, in parse_config_files
    pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
  File "D:\ProgramFiles\anaconda\envs\winter\lib\site-packages\setuptools\config\pyprojecttoml.py", line 85, in apply_configuration
    config = read_configuration(filepath, True, ignore_option_errors, dist)
  File "D:\ProgramFiles\anaconda\envs\winter\lib\site-packages\setuptools\config\pyprojecttoml.py", line 153, in read_configuration
    validate(subset, filepath)
  File "D:\ProgramFiles\anaconda\envs\winter\lib\site-packages\setuptools\config\pyprojecttoml.py", line 74, in validate
    raise ValueError(f"{error}\n{summary}") from None
ValueError: invalid pyproject.toml config: `project`.
configuration error: `project` must not contain {'repository'} properties

进程已结束，退出代码为 1
I dont know how to deal with it. I have already created an new envs and installed depends. But it comes out

**Comment by omigeft** [comment]
Don't run this `setup.py`. We will fix it when we are free.
